apiVersion: v1
kind: Service
metadata:
  name: deptest
  namespace: namespace-workflow-1685312950679
spec:
  type: LoadBalancer
  selector:
    app: deptest
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000